pipelines:
  default:
  - step:
      name: "PHP CodeSniffer"
      image: php:7.2-cli
      script:
      - cd backend
      - php phpcs.phar .
  - step:
      name: "PHPUnit"
      image: epcallan/php7-testing-phpunit:7.2-phpunit7
      script:
      - cd backend
      - phpunit
  - step:
      name: "ESLint"
      image: node:8-alpine
      caches:
      - frontend-node-modules
      script:
      - cd frontend
      - yarn
      - yarn run lint

definitions:
  caches:
    frontend-node-modules: frontend/node_modules
