pipelines:
  branches:
    dev/backend*:
    - step:
        name: "PHP CodeSniffer and PHPUnit"
        image:
            name: foodieconnectorphp/foodie-connector-php:test-php
            username: $DOCKER_HUB_USERNAME
            password: $DOCKER_HUB_PASSWORD
            email: $DOCKER_HUB_EMAIL
        caches:
        - backend-vendor
        script:
        - /entrypoint.sh
        - cd backend
        - phpcs .
        - composer install
        - cp .env.example .env
        - php artisan key:generate
        - phpunit
    dev/frontend*:
    - step:
        name: "ESLint"
        image: node:8-alpine
        caches:
        - frontend-node-modules
        script:
        - cd frontend
        - yarn
        - yarn lint
        - yarn test
    release/ci/docker-test-php:
    - step:
        name: Build docker for PHP tests
        services:
        - docker
        caches:
        - docker
        script:
        - cd docker/test-php
        - docker build -t ${IMAGE_NAME}:test-php .
        - ../docker-login.sh
        - docker push ${IMAGE_NAME}:test-php
    
definitions:
  caches:
    frontend-node-modules: frontend/node_modules
    backend-vendor: backend/vendor
