pipelines:
  default:
  - step:
      name: "PHP CodeSniffer"
      image: php:7.2-cli
      script:
      - cd backend
      - php phpcs.phar .
  - step:
      name: "PHPUnit"
      image:
        name: foodieconnectorphp/foodie-connector-php:php-testing-latest
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASSWORD
        email: $DOCKER_HUB_EMAIL
      caches:
      - backend-vendor
      script:
      - /usr/bin/redis-server --daemonize yes
      - cd backend
      - php composer.phar install
      - cp .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit
  - step:
      name: "ESLint"
      image: node:8-alpine
      caches:
      - frontend-node-modules
      script:
      - cd frontend
      - yarn
      - yarn run lint

definitions:
  caches:
    frontend-node-modules: frontend/node_modules
    backend-vendor: backend/vendor
