steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/${PROJECT_ID}/release:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/release:${BUILD_ID}', '-t', 'gcr.io/${PROJECT_ID}/release:latest', '--cache-from', 'gcr.io/${PROJECT_ID}/release:latest', '--build-arg', 'COMMIT_SHA=$COMMIT_SHA', '--build-arg', 'BUILD_ID=$BUILD_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/release:${BUILD_ID}']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', 'app-test', 'app=gcr.io/${PROJECT_ID}/release:${BUILD_ID}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
images: ['gcr.io/${PROJECT_ID}/release:latest']
