version: '3.1'
services:
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /docker/mysql/data:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy
      