version: '3'
services:
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - /docker/nginx/sites-available:/etc/nginx/sites-enabled
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/log/nginx:/var/log/nginx
      - /docker/certbot/etc:/etc/letsencrypt

networks:
  default:
    external:
      name: webproxy